// <auto-generated />
namespace CargoMate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TripTypeImageUrlColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TripTypeImageUrlColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201712301213119_Trip Type ImageUrl Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
